kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: prueba
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
   # command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    ports:
    - containerPort: 80
      protocol: TCP
      name: http
