apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-volum-sc-lh
  namespace: prueba
  labels:
    app: nginx-longhorn
    storage-type: longhorn
    tier: storage
  annotations:
    description: "PVC usando Longhorn para almacenamiento distribuido"
    training-module: "clase5-storage"
    longhorn.io/replica-count: "2"  # Número de réplicas
spec:
  accessModes:
  - ReadWriteOnce  # Longhorn usa RWO por defecto
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-lh
  namespace: prueba
  labels:
    app: nginx-longhorn
    component: webserver
    tier: frontend
    storage-demo: longhorn
  annotations:
    description: "Pod de prueba con almacenamiento Longhorn"
    training-module: "clase5-storage"
spec:
  containers:
  - name: nginx
    image: nginx:1.25-alpine
    ports:
    - containerPort: 80
      protocol: TCP
      name: http
    # Configuración de recursos
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    # Health checks
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    # Montaje del volumen
    volumeMounts:
    - name: web-content
      mountPath: "/usr/share/nginx/html"
      subPath: nginx
  volumes:
  - name: web-content
    persistentVolumeClaim:
      claimName: nginx-volum-sc-lh
  restartPolicy: Always
