apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: longhorn-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
