apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ippool 
  namespace: metallb-system
spec:
  addresses:
  - 172.27.101.240 - 172.27.101.249
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
